// Generate packages/web/.env.local and packages/agent/.env from the local
// deployment JSON written by DeployLocal.s.sol. Keeps the frontend + agent in
// lock-step with whatever addresses anvil just produced.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const deployPath = join(root, "packages/contracts/deployments/local.json");
const d = JSON.parse(readFileSync(deployPath, "utf8"));

// Well-known PUBLIC anvil account #0 — LOCAL ONLY, never reuse on a real network.
const ANVIL_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";

const web = `# generated by scripts/gen-env.mjs — LIVE mode against local anvil (chain 31337)
NEXT_PUBLIC_CHAIN_ID=31337
NEXT_PUBLIC_ENGINE_ADDRESS=${d.engine}
NEXT_PUBLIC_VAULT_ADDRESS=${d.vault}
NEXT_PUBLIC_ADAPTER=${d.adapter}
NEXT_PUBLIC_SOURCE_ASSET=${d.source}
NEXT_PUBLIC_TARGET_ASSET=${d.target}
NEXT_PUBLIC_PROTECTED_USER=${d.protectedUser}
# NEXT_PUBLIC_WC_PROJECT_ID=
`;
writeFileSync(join(root, "packages/web/.env.local"), web);

const agent = `# generated by scripts/gen-env.mjs — keeper loop vs local anvil (account #0, LOCAL ONLY)
CHAIN_ID=31337
RPC_URL=http://127.0.0.1:8545
RISK_ENGINE_ADDRESS=${d.engine}
AEGIS_VAULT_ADDRESS=${d.vault}
PRICE_FEED_ADDRESS=${d.priceFeed}
EXPECTED_PRICE=200000000000
KEEPER_PRIVATE_KEY=${ANVIL_KEY}
PROTECTED_USER=${d.protectedUser}
POLL_INTERVAL_MS=15000
`;
writeFileSync(join(root, "packages/agent/.env"), agent);

console.log("✓ wrote packages/web/.env.local and packages/agent/.env from", deployPath);
